AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >-
  pulpo-bc-openaid-api

  AWS SAM Business case project with Openaid API integration

Resources:
  HelloLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/hello-lambda.handler
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 100
      Description: A Lambda function that returns a static string.
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        HelloLambda:
          Type: Api
          Properties:
            Path: /hello
            Method: GET
